import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "./components/Navber";
import Tost from "./components/Tost";
import { SessionProvider } from "next-auth/react";
import NextAuthProvider from "@/Providers/NextAuthProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light" data-arp="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >



        <NextAuthProvider>
          <Navber></Navber>
          <div className="max-w-[1400px] mx-auto">



            {children}


            <Tost></Tost>


          </div>


          <footer className="bg-[#234C6A] text-white py-6 text-center">
            © 2025 Your Company. All rights reserved.
          </footer>
        </NextAuthProvider>





      </body>


    </html>
  );
}
